// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeindtmtrqcvfmsgrzvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9laW5kdG10cnFjdmZtc2dyenZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzQyMTksImV4cCI6MjA3MTA1MDIxOX0.TX7JgTtYnxiF0eUkEXyIpS-0VPjtwO0PuHBO5T0dOho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});